### ISSUE TITLE
Installation is failed using latest Homebrew

### ISSUE THREAD

**Issue by kawarimidoll** [gingerbeardman/Emojipedia#18]
**Describe the bug**

The command `brew cask install` in `README.md` doesn't work now because of update of Homebrew.
This is not a bug of this app, but the document needs to be fixed.

**To Reproduce**

Run `brew cask install emojipedia`.

**Expected behavior**

Installation is succeeded.

**Screenshots**

![Calling brew cask is disabled](https://user-images.githubusercontent.com/8146876/111925808-a4b2de00-8aed-11eb-8b1e-a0873b827261.png)

**Desktop (please complete the following information):**
 - OS: macOS 11.2.3
 - Browser: not relevant

**Additional context**

homebrew discussions: [Error: Calling brew cask install is disabled! · Discussion #340 · Homebrew/discussions](https://github.com/Homebrew/discussions/discussions/340#discussioncomment-232364)

> `brew cask <command>` was deprecated in favor of `brew <command> --cask` in Homebrew 2.6.0. Now that 2.7.0 has been released, they have been disabled.

homebrew blog: [2.6.0 — Homebrew](https://brew.sh/2020/12/01/homebrew-2.6.0/)

> All brew cask commands have been deprecated in favour of brew commands (with --cask) when necessary

**Comment by gingerbeardman** [comment]
Thanks, I've merged your PR.

Note: I no longer support the brew project due to instances of their team members bullying contributors with no accountability.
