### ISSUE TITLE
Can't display some emoji definition

### ISSUE THREAD

**Issue by poweruser82** [gingerbeardman/Emojipedia#7]
In OS X 10.10.5 neither Dictionary.app nor the pop up can display the definition of some emoji.
I.e.:
* `😅` `Smiling Face With Open Mouth & Cold Sweat`.
* `😆` `Smiling Face With Open Mouth & Closed Eyes`

I suppose this may be due to unescaped `&` in the `Emoji.xml` file.

**Comment by gingerbeardman** [comment]
Thanks for the bug report!

This is fixed in the latest release https://github.com/gingerbeardman/Emojipedia/releases/tag/20170424

**Comment by gingerbeardman** [comment]
Have also updated the 20170424 release to include this—thanks again!
